// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Blog {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    cover: { data: Media };
    content: any;
    slug: string;
    locale: string;
    localizations?: { data: Blog[] };
  };
}
export interface Blog_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  cover: Media;
  content: any;
  slug: string;
  locale: string;
  localizations?: Blog[];
}

export interface Blog_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  cover: number;
  content: any;
  slug: string;
  locale: string;
  localizations?: Blog[];
}

export interface Blog_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  cover: AdminPanelRelationPropertyModification<Media>;
  content: any;
  slug: string;
  locale: string;
  localizations?: Blog[];
}
